import type { Metadata } from "next";
import Header from "../feature/Header/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Hono | nextjs",
  description: "Generated by hono",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
          <Header />
        </div>
        {children}
      </body>
    </html>
  );
}
