import type { Metadata } from "next";
import Header from "../feature/Header/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "machohub",
  description: "Generated by hono",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/kurage.png" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
