name = "backend"
main= "src/index.ts"
# type = "webpack"
# route = ''
# zone_id = ''
# usage_model = "bundled"
compatibility_flags = ["nodejs_compat_v2", "nodejs_als"]
workers_dev = true
compatibility_date = "2024-09-23"
